### ISSUE TITLE
IPv6 does not seem to be well supported

### ISSUE THREAD

**Issue by thierryba** [jazzband/django-user-sessions#119]
## Expected Behavior
connecting with ipv6 would just work

## Current Behavior
if I connect with IPv6, I'm getting this in my log
```
Traceback (most recent call last):
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/utils/deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/user_sessions/middleware.py", line 56, in process_response
    request.session.save()
  File "/usr/local/filewave/python/lib/python3.7/site-packages/user_sessions/backends/db.py", line 81, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/filewave/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: invalid input syntax for type inet: "fe80::c71:cfcd:6cda:c9a%en0"
LINE 1: ...06-24T13:54:42.365313+00:00'::timestamptz, "ip" = 'fe80::c71...
```

## Possible Solution
the %en0 is the scope id and does not seem to be supported at least by Postgres.. Could we discard it?

## Steps to Reproduce (for bugs)
1. enable ipv6
2. connect to an application using it

## Context
I'd want to support ipv6 for my server.

## Your Environment
* Browser and version: native application
* Python version: 3.7.7
* Django version: 2.2
* django-otp version:
* django-user-sessions version: 1.6
* Link to your project: N/A
* apache 2.4.X
* mod_wsgi 4.6.5

**Comment by mbeijen** [comment]
django-user-sessions supports IPv6, and for me it 'just works'. 

![ip6](https://user-images.githubusercontent.com/659504/85660398-de1d0100-b6b5-11ea-94c5-2ea20ab7b906.jpg)

Apart from that, django-user-sessions just uses `meta.REMOTE_ADDR` in Django, which comes from WSGI, where `REMOTE_ADDR` is defined in the CGI RFC in [RFC3874 par 4.1.8](https://tools.ietf.org/html/rfc3875#section-4.1.8):

> The REMOTE_ADDR variable MUST be set to the network address of the
>   client sending the request to the server.
>
>      REMOTE_ADDR  = hostnumber
>      hostnumber   = ipv4-address | ipv6-address
>      ipv4-address = 1*3digit "." 1*3digit "." 1*3digit "." 1*3digit
>      ipv6-address = hexpart [ ":" ipv4-address ]
>      hexpart      = hexseq | ( [ hexseq ] "::" [ hexseq ] )
>      hexseq       = 1*4hex *( ":" 1*4hex )

so in your case, `REMOTE_ADDR` has an invalid value; adding the scope to the address is not valid. This is set by one of your components. I'd guess it's not Apache or mod_wsgi, my bet is that it's introduced by some Django middleware. Please inspect your middleware and find out where the scope id is added. And if you want a quick workaround, you can add your own django middleware that 'fixes up' the value.

**Comment by mbeijen** [comment]
I'm closing the issue, this is a configuration issue on your end and outside of the scope of django-user-sessions.
