### ISSUE TITLE
Don't depend on pkg_resources

### ISSUE THREAD

**Issue by ataylor32** [jazzband/django-user-sessions#185]
## Expected Behavior

I should be able to run a command like `python manage.py shell` without any errors.

## Current Behavior

```
[ERROR] management_commands File "/var/www/example.com/manage.py", line 33: Management command error: manage.py shell
Traceback (most recent call last):
  File "/var/www/example.com/manage.py", line 31, in main
    execute_from_command_line(sys.argv)
  File "/var/www/example.com/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/www/example.com/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/var/www/example.com/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/example.com/venv/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/example.com/venv/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/www/example.com/venv/lib/python3.12/site-packages/user_sessions/__init__.py", line 1, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```

## Your Environment
* Python version: 3.12.3
* Django version: 4.2.11
* django-user-sessions version: 2.0.0

Relevant: https://github.com/python/cpython/issues/95299

**Comment by WhyNotHugo** [comment]
`pkg_resources` is used to read the current package version.

We should probably write the version into a file at build time instead with something like:

```toml
[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
write_to = "user_sessions/version.py"
version_scheme = "no-guess-dev"
```

**Comment by aradfarahani** [comment]
The error you're encountering, `ModuleNotFoundError: No module named 'pkg_resources'`, typically occurs when the `setuptools` package is not installed or is not properly configured in your Python environment. Here are some steps to resolve this issue:

### Steps to Fix the Error

1. **Install or Upgrade `setuptools`**:
   Ensure that `setuptools` is installed and up-to-date. You can do this by running the following commands:
   ```bash
   pip install --upgrade setuptools
   ```

2. **Uninstall and Reinstall `setuptools`**:
   If the above step doesn't work, try uninstalling and then reinstalling `setuptools`:
   ```bash
   pip uninstall -y setuptools
   pip install setuptools
   ```

3. **Upgrade `pip`, `setuptools`, and `wheel`**:
   Sometimes, upgrading `pip`, `setuptools`, and `wheel` can resolve the issue:
   ```bash
   # For Unix/macOS
   python3 -m pip install --upgrade pip setuptools wheel

   # For Windows
   py -m pip install --upgrade pip setuptools wheel
   ```

4. **Create a Virtual Environment**:
   If the issue persists, try creating a new virtual environment and installing the necessary packages within it:
   ```bash
   # For Unix/macOS
   python3 -m venv my_env
   source my_env/bin/activate

   # For Windows
   py -m venv my_env
   my_env\Scripts\activate

   # Then install the required packages
   pip install django django-user-sessions
   ```

### Example Configuration for `setuptools_scm`
If you need to write the version into a file at build time, you can configure `setuptools_scm` as follows:

1. **Add `setuptools_scm` to your `pyproject.toml`**:
   ```toml
   [build-system]
   requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

   [tool.setuptools_scm]
   write_to = "user_sessions/version.py"
   version_scheme = "no-guess-dev"
   ```

2. **Modify `__init__.py`**:
   In your `__init__.py`, use the following code to import the version:
   ```python
   from . import version

   __version__ = version.version
   ```

By following these steps, you should be able to resolve the `ModuleNotFoundError: No module named 'pkg_resources'` and run `python manage.py shell` without any errors.

**Comment by thierryba** [comment]
This was fixed 2 years ago with fe1e1a5.
Could we have an official release maybe?

**Comment by rphlo** [comment]
Also now with latest version of setuptools, it throw a warning:

`UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.`

**Comment by benwhalley** [comment]
This ticket says PR welcome, but it seems like it's already been fixed? Is it possible to get a release which includes this commit?  https://github.com/jazzband/django-user-sessions/commit/fe1e1a5ed19cc4ec5addc4325e5309b2a43494ac

**Comment by N1K1TAS95** [comment]
Hi there!
Any updates?
I have similar issue as @rphlo

**Comment by al-beton** [comment]
Could the fix in fe1e1a5 get onto PyPI? As far as I can tell the release is already made, it just never reached PyPI:

- Tags 3.0.0 to 3.0.3 were pushed on 2025-09-26. The release workflow failed for the first three and succeeded for 3.0.3 (https://github.com/jazzband/django-user-sessions/actions/runs/18042475265), which uploads to jazzband.co.
- Jazzband uploads need a project lead to release them from https://jazzband.co/projects/django-user-sessions (the page shows 4 uploads waiting). PyPI still lists 2.0.0 from December 2022.

Since setuptools 81 removes `pkg_resources` entirely, 2.0.0 will stop importing at all rather than just warning, so a PyPI release of 3.0.3 would unblock everyone on this thread. @ricco386, as the listed lead, would you be able to release it from the Jazzband project page? Happy to help with anything else that is needed.

For anyone else in the meantime: pinning to the 3.0.3 tag commit as a git dependency (`django-user-sessions @ git+https://github.com/jazzband/django-user-sessions@2811b95d7fe76eb00666e3fecaf8133bcc5e3da2`) works with Django 5.2 and installs as version 3.0.3.
